version: '3'
services:
  app:
    build: .
    network_mode: "host"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AWS_REGION=ap-northeast-2
      # AWS 자격증명
      - CLOUD_AWS_CREDENTIALS_ACCESS_KEY=AKIA3FLD3UNUJIUZXIHM
      - CLOUD_AWS_CREDENTIALS_SECRET_KEY=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
      - CLOUD_AWS_REGION_STATIC=ap-northeast-2
      - CLOUD_AWS_S3_BUCKET=sooktin-storage
      # DB 설정
      - SPRING_DATASOURCE_URL=jdbc:mysql://sooktin-db.cj4ey4aiefr4.ap-northeast-2.rds.amazonaws.com:3306/sooktin?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=dbcoals!47
      # security 설정
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=sooktin0908
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - monitoring
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

#  prometheus:
#    image: prom/prometheus
#    container_name: prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana_data:
networks:
  monitoring:
    driver: bridge
