server {
    listen 80;
    listen 443 ssl;
    server_name sooktin.duckdns.org;

    # SSL 설정
    ssl_certificate /etc/letsencrypt/live/sooktin.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sooktin.duckdns.org/privkey.pem;

    # 불필요한 PHP 관련 요청 차단 (공격 시도 차단)
    location ~* (\.php$|/index.php|/think|/public/index.php|/vendor|/runtime) {
        return 403;
    }

    # 민감한 경로 차단 (phpMyAdmin, WP Admin 등)
    location ~* (/phpmyadmin|/admin|/wp-admin|/wp-login.php) {
        return 403;
    }

    # SQL Injection 및 XSS 공격 차단
    location ~* "(select|union|insert|delete|update|drop|alter|create|exec|cast|declare|sleep|benchmark)" {
        return 403;
    }

    location /v3/api-docs {
        proxy_pass http://localhost:8080/v3/api-docs;
        proxy_pass http://localhost:8080/swagger-ui.html;
        proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization $http_authorization; # Authorization 헤더 전달
    }
    location /swagger-ui {
        proxy_pass http://localhost:8080/swagger-ui;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
    }

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 리다이렉션 방지
        proxy_redirect off;

        # HTTP 메서드 보존
        proxy_method $request_method;
        proxy_pass_request_headers on;
        proxy_pass_request_body on;

        # CORS 설정
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
    }

    # 로그 설정 (보안 및 디버깅 목적)
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}