jwt:
    issuer: sooktin
    access-expiration: 1209600000  # 1시간
    refresh-expiration: 1209600000  # 14일
    secret-key: cThIIoDvwdueQB468K5xDc5633seEFoqwxjF_xSJyQQ
server:
  error:
    include-binding-errors: always
    include-message: always
  address: 0.0.0.0
  port: 8080
cloud:
  aws:
    credentials:
      access-key: AKIA3FLD3UNUJIUZXIHM
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: sooktin-storage
spring:
  cache:
    type: redis
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  application:
    name: sooktin
  datasource:
    url: jdbc:mysql://sooktin-db.cj4ey4aiefr4.ap-northeast-2.rds.amazonaws.com:3306/sooktin?serverTimezone=UTC
    username: admin
    password: dbcoals!47
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  security:
    user:
      name: admin
      password: sooktin0908
      roles: ADMIN
  mail:
    host: smtp.gmail.com
    port: 587
    username: dudghkrkwhgek@gmail.com
    password: mwbu meie oonk rdba
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
  chat:
    queue: 
      name: chat.queue
    
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    display-request-duration: true
    enabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, health
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    enable:
      all: true
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
logging:
  level:
    com:
      sooktin:
        backend:
          auth: DEBUG
          global:
            exception: TRACE
    org:
      springdoc: TRACE
      springframework:
        messaging: DEBUG
        web:
          socket: DEBUG
        security: DEBUG
        cache: DEBUG
      data:
        redis: DEBUG
