name: Deploy to EC2

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-2

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2 using git pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app
          git pull https://${{ secrets.GITHUB_USERNAME }}:${{ secrets.GITHUB_TOKEN }}@github.com/chaeminyu/backend.git main
          chmod +x gradlew
          ./gradlew build -x test
          chmod +x deploy.sh
          ./deploy.sh
