name: Deploy to EC2

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-2
  REPO_URL: https://github.com/sooktin/backend_repository.git

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2 using git pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app
          git pull https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/sooktin/backend_repository.git main || echo "Git pull failed, but continuing deployment"
          # 서버에 이미 Java가 있으면 아래 명령어를 실행할 수 있음
          if command -v java &> /dev/null; then
            chmod +x gradlew
            ./gradlew build -x test
          else
            echo "Skipping Gradle build as Java is not available"
          fi
          chmod +x deploy.sh
          ./deploy.sh
